FHM/Controllers/ApplicationUserViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FHM.Models;
using FHM.Models.ApplicationUserViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FHM.Controllers
{
    public class ApplicationUserViewController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IApplicationUserViewRepo _context;

        public ApplicationUserViewController (IApplicationUserViewRepo context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var _Roles = _context.GetAllRoles();
            var _UsersNoRole = _context.GetAllUsersNoRole();
            var _Customers = _context.GetAllCustomers();
            var _Organizers = _context.GetAllOrganizers();
            var _Employees = _context.GetAllEmployees();
            var _Admins = _context.GetAllAdmins();

            var applicationUserView = new ApplicationUserView()
            {
                Title = "Adjust Roles",
                Roles = _Roles,
                UsersNoRole = _UsersNoRole,
                Customers = _Customers,
                Organizers = _Organizers,
                Employees = _Employees,
                Admins = _Admins
            };

            return View(applicationUserView);

        }
        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser user = _context.findUser(id);
            var roleIds = _userManager.GetRolesAsync(user).Result;
            List<AppRole> roles = new List<AppRole>();

            foreach (string element in roleIds)
            {
                var role = _context.findRole(element);
                roles.Add(role);
            }

            if (user == null)
            {
                return NotFound();
            }
            if (roles == null)
            {
                return NotFound();
            }

            var appUserAndRoleView = new ApplicationUserView()
            {
                Roles = roles,
                User = user
            };

            return View(appUserAndRoleView);
        }
        [HttpPost]
        public IActionResult Delete(string userID, string AppRoleID)
        {
            if (ModelState.IsValid)
            {
                _context.DropRole(userID, AppRoleID);
                return RedirectToAction("Index");
            }
            return View(userID);
        }
        public IActionResult Add(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser user = _context.findUser(id);
            IEnumerable<AppRole> roles = _context.GetAllRoles();
            if (user == null)
            {
                return NotFound();
            }
            var appUserAndRoleView = new ApplicationUserView()
            {
                Roles = roles,
                User = user
            };

            return View(appUserAndRoleView);
        }
        [HttpPost]
        public IActionResult Add(string userID, string AppRoleID)
        {
            if (ModelState.IsValid)
            {
                _context.AddRole(userID, AppRoleID);
                return RedirectToAction("Index");
            }
            return View(userID);
        }
    }
}

FHM/Controllers/FormatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FHM.Data;
using FHM.Models.FormatModels;
using FHM.Models.FormatViewModels;

namespace FHM.Controllers
{
    public class FormatsController : Controller
    {
        private readonly IFormatRepository _context;

        public FormatsController(IFormatRepository appDbContext)
        {
            _context = appDbContext;
        }

        // GET: Formats
        public  IActionResult Index()
        {
            return View(_context.GetAllFormats());
        }

        // GET: Formats/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var format = _context.GetFormatByID(id);
            if (format == null)
            {
                return NotFound();
            }

            return View(format);
        }

        // GET: Formats/Create
        public IActionResult Create()
        {
            var games = _context.GetAllGames();

            var viewModel = new FormatFormViewModel
            {
            Games = games
            };
            return View(viewModel);
        }

        // POST: Formats/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public  IActionResult Create(Format format)
        {
            if (ModelState.IsValid)
            {
                _context.AddFormat(format);
                return RedirectToAction("AddGameComplete");
            }
            return View(format);
        }

        public IActionResult AddGameComplete()
        {
            return View();
        }
  

        // GET: Formats/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var format =  _context.GetFormatByID(id);
            if (format == null)
            {
                return NotFound();
            }

            return View(format);
        }
        [HttpPost]
        public IActionResult Delete(int formatID)
        {
            if (ModelState.IsValid)
            {
                _context.DeleteFormat(formatID);
                return RedirectToAction("Index");
            }
            return View(formatID);
        }
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var format = _context.GetFormatByID(id);
            if (format == null)
            {
                return NotFound();
            }
            var games = _context.GetAllGames();

            var viewModel = new FormatFormViewModel
            {
            FormatID = id,
            FormatName = format.FormatName,
            FormatDescription = format.FormatDescription,
            FormatLink = format.FormatLink,
            GameID = format.GameID,
            Games = games
            };
            return View(viewModel);

        }
        [HttpPost]
        public IActionResult Edit(Format format)
        {
            int formatID = format.FormatID;
            if (ModelState.IsValid)
            {
                _context.EditFormat(format);
                return RedirectToAction("Details",new {id = formatID});
            }
            return View(format.FormatID);
        }
    }
}

FHM/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FHM.Models.GameModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using FHM.Models.GameViewModels;
using FHM.Models.FormatModels;
using FHM.Models.TournamentModels;

namespace FHM.Controllers
{
    public class GameController : Controller
    {
        private readonly IGameRepository _gameRepository;
        private readonly IFormatRepository _formatRepository;
        private readonly ITournamentRepository _tournamentRepository;

        public GameController(IGameRepository gameRepository, IFormatRepository formatRepository, ITournamentRepository tournamentRepository)
        {
            _gameRepository = gameRepository;
            _formatRepository = formatRepository;
            _tournamentRepository = tournamentRepository;
        }

        public IActionResult Index()
        {
            var games = _gameRepository.GetAllGames().OrderBy(g => g.GameName);

            var gameViewModel = new GameViewModel()
            {
                Title = "Games at Four Horsemen",
                Games = games.ToList()
            };

            return View(gameViewModel);
        }

        public IActionResult GameDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = _gameRepository.GetGameByID(id);
            if (game == null)
            {
                return NotFound();
            }

            var gameViewModel = new GameViewModel()
            {
                Game = game,
                Formats = _formatRepository.GetAllFormats().Where(f => f.GameID == game.GameID).ToList(),
                Tournaments = _tournamentRepository.GetAllTournaments().Where(f => f.GameID == game.GameID).ToList()
            };

            return View(gameViewModel);
        }
        [Authorize]
        public IActionResult AddGame()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult AddGame(Game game)
        {
            if (ModelState.IsValid)
            {
                _gameRepository.AddGame(game);
                return RedirectToAction("AddGameComplete");
            }
            return View(game);
        }

        public IActionResult AddGameComplete()
        {
            return View();
        }
                // GET: Formats/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = _gameRepository.GetGameByID(id);
            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }
        [HttpPost]
        public IActionResult Delete(int gameID)
        {
            if (ModelState.IsValid)
            {
                _gameRepository.DeleteGame(gameID);
                return RedirectToAction("Index");
            }
            return View(gameID);
        }
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = _gameRepository.GetGameByID(id);
            if (game == null)
            {
                return NotFound();
            }
            var games = _gameRepository.GetAllGames();

            return View(game);

        }
        [HttpPost]
        public IActionResult Edit(Game game)
        {
            int gameID = game.GameID;
            if (ModelState.IsValid)
            {
                _gameRepository.EditGame(game);
                return RedirectToAction("GameDetails", new { id = gameID });
            }
            return View(game.GameID);
        }

    }
}

FHM/Controllers/PlayerIDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FHM.Models;
using FHM.Models.PlayerIDModel;
using FHM.Models.PlayerIdViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FHM.Controllers
{
    public class PlayerIDController : Controller
    {
        private readonly IPlayerIDRepository _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public PlayerIDController(IPlayerIDRepository context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            var playerIDs = _context.GetAllPlayerIDsByPlayer(user.Id);
            if (playerIDs == null)
            {
                return RedirectToAction("Create");
            }
            else
            {
                return View(playerIDs);
            }
        }

        public async Task<IActionResult> Create()
        {
            var user = await _userManager.GetUserAsync(User);
            var games = _context.GetAllGames();
            var players = _context.GetAllPlayers();

            var viewModel = new PlayerIdViewModel
            {
                Games = games,
                Players = players,
                UserID = user.Id
            };
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Create(PlayerIdViewModel playerID)
        {
            if (ModelState.IsValid)
            {
                _context.AddPlayerIdView(playerID);
                return RedirectToAction("Index");
            }
            return View(playerID);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PlayerID playerID = _context.GetPlayerIDByID(id);
            if (playerID == null)
            {
                return NotFound();
            }

            return View(playerID);
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            if (ModelState.IsValid)
            {
                _context.DeletePlayerID(id);
                return RedirectToAction("Index");
            }
            return View(id);
        }
    }
}

FHM/Views/Shared/_FooterPartial.cshtml
<footer>
    <div class="container">
        <p class="two_columns first">&copy; 2018 - Four Horsemen Comics and Gaming<br>
            9201 Mall Rd<br>
            Morgantown, West Virginia 26501<br>
            (304) 581-4461<br>
            Email: <a href="mailto:info@fourhorsemencomics.com">info@fourhorsemencomics.com</a></p>
        <p class="two_columns last">
            Store Hours:<br>
            Monday-Friday: 10AM-9PM<br>
            Saturday: 10AM-9PM<br>
            Sunday: 12PM-6PM<br>
        </p>
    </div>
</footer>

FHM/Views/Shared/_Frontpage.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Four Horsemen Comics and Gaming</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/styles.css" />
        <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One|Rubik:300,400,700,900" rel="stylesheet">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    
</head>

@await Html.PartialAsync("_HeaderPartial")

<body>
    
    @RenderBody()

    <footer style="margin-top:0px;">
    <div class="container">
        <p class="two_columns first">&copy; 2018 - Four Horsemen Comics and Gaming<br>
            9201 Mall Rd<br>
            Morgantown, West Virginia 26501<br>
            (304) 581-4461<br>
            Email: <a href="mailto:info@fourhorsemencomics.com">info@fourhorsemencomics.com</a></p>
        <p class="two_columns last">
            Store Hours:<br>
            Monday-Friday: 10AM-9PM<br>
            Saturday: 10AM-9PM<br>
            Sunday: 12PM-6PM<br>
        </p>
    </div>
</footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

FHM/Views/Shared/_HeaderPartial.cshtml
<header>
    <div class="masthead">
        <div class="container">
            <a asp-area="" asp-controller="Home" asp-action="Index" alt-tag="Four Horsemen Logo"><img class="header_logo" src="/images/4hm_wordmark.svg" alt-text="Four Horsemen Logo"/></a>
            @await Html.PartialAsync("_LoginPartial")
        </div>
    </div>
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <!-- <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li> -->
                    <li><a asp-area="" asp-controller="Game" asp-action="Index">Games</a></li>
                    <li><a asp-area="" asp-controller="Tournament" asp-action="Index">Events</a></li>
                    <li><a asp-area="" asp-controller="ApplicationUserView" asp-action="Index">Roles</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="PlayerID" asp-action="Index">My IDs</a></li>
                        <li><a asp-area="" asp-controller="Formats" asp-action="Index">All Formats</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>

FHM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Four Horsemen Comics and Gaming</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/styles.css" />
        <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One|Rubik:300,400,700,900" rel="stylesheet">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    
</head>

@await Html.PartialAsync("_HeaderPartial")

<body>
    
    @RenderBody()

    @await Html.PartialAsync("_FooterPartial")


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>